---
version: "2.1"
services:
  smileBot:
    environment:
    - LANG=en_US.UTF-8
    image: smilebot:latest
    container_name: smilebot
    volumes:
      - $PWD:/etc/smilebot
    restart: unless-stopped
